version: "3.8"

networks:
  loki:

services:

  # Since the Loki containers are running as user 10001 and the mounted data volume is owned by root,
  # Loki would not have permissions to create the directories.
  # Therefore the init container changes permissions of the mounted directory.
  # init:
  #   image: grafana/loki:2.6.1
  #   user: root
  #   entrypoint:
  #     - "chown"
  #     - "10001:10001"
  #     - "/loki"
  #   volumes:
  #     - ./loki:/loki
  #   networks:
  #     - loki

  grafana:
    image: grafana/grafana:9.1.6
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    volumes:
      - ./config/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yml
      - grafana:/var/lib/grafana
    networks:
      - loki


  # for testing purposes only, disable in production
  web-app:
    image: e2xen/devops-pythonapp:latest
    volumes:
      - ./logs/:/code/log/
    ports:
      - "80:80"

  promtail:
    image: grafana/promtail:2.6.1
    volumes:
      - ./logs/:/var/log/
      - ./config:/etc/promtail/
    ports:
      - "9080:9080"
    command: -config.file=/etc/promtail/promtail.yaml
    networks:
      - loki

  loki:
    image: grafana/loki:2.6.1
    # volumes:
    #   - ./config:/etc/loki/
    ports:
      - "3100"
      - "7946"

    command: "-config.file=/etc/loki/local-config.yaml"
    networks:
      - loki

volumes:
  grafana: